Implement EditBookScreen logic and UI for editing and deleting books
BookswapEPFL/Bookswap pull request #138
Opened 2024-10-31 09:52 UTC by LeniCadorinEpfl

This PR introduces the `EditBookScreen`, which allows users to edit book details and delete books.

**Key components include:**

**EditBookScreen UI Implementation:** A comprehensive layout for editing book information, including title, author, description, genre, rating, and language.

<img width="221" alt="EditBookScreenUI" src="https://github.com/user-attachments/assets/a8a806a2-07b1-42a1-a3e2-9a8dfb4e3885">

**Core Logic Integration:** Utilized the `BooksFirestoreRepository` for data management, with functions to update and delete books, along with validation checks for required fields.

**Error Handling:** Added Toast notifications for handling validation errors and update failures, ensuring a good user experience.

**Tests for EditBookScreen:** Added tests in EditBookScreenTest.kt to ensure correct functionality

**Checklist:**
- [ ] CI passes
- [ ] Structure is correct
- [ ] Tests for the added code are complete

2024-10-31 11:05 UTC, TheoSchlaeppi requested changes
Here are my thoughts and suggestions:

1. **EditBookScreen UI Implementation**:
   - The layout for editing book information is comprehensive and includes fields for title, genre, author, description, rating, photo, and language.
   - Consider verifying the correct initial values in your tests to ensure the UI displays the expected data when loading the screen.

2. **Core Logic Integration**:
   - The integration with `BooksFirestoreRepository` for data management is well done. Functions for updating and deleting books are clearly defined.
   - It would be beneficial to add a test to confirm that the save button correctly calls the repository's `updateBook` function with the right parameters.

3. **Error Handling**:
   - The inclusion of Toast notifications for validation errors and update failures enhances the user experience. Ensure that error messages are clear and helpful to the user.
   - Additionally, consider adding tests for scenarios where fields are left blank to verify that appropriate error messages are displayed.

4. **Typos**
   - There are some typos that i have flag with comments on the code.

### Overall Impression

The implementation of `EditBookScreen` is well-structured and addresses key functionalities for editing book details.I appreciate how you structured the code, making it easy to integrate additional features in the future.

Thank you for your work on this! Looking forward to seeing the improvements.

2024-11-01 01:34 UTC, LeniCadorinEpfl commented
Thank you for the review. I have taken your suggestions into account and removed the different typo.
For the part:
> Consider verifying the correct initial values in your tests to ensure the UI displays the expected data when loading the screen.
These test are already present in my code, the test name is 'inputsHaveInitialValue`.

2024-11-07 13:55 UTC, LeniCadorinEpfl commented on app/src/main/java/com/android/bookswap/ui/books/edit/EditBookScreen.kt
> +                          OnSucess = { navigationActions.goBack() },
This is from Matias's code, but I can actually change it.

2024-11-07 14:16 UTC, TheoSchlaeppi approved these changes
Looks good for me !

2024-11-07 14:18 UTC, merged