Feature implement the screen that new user will see at first when lo…
BookswapEPFL/Bookswap pull request #195
Opened 2024-11-11 17:28 UTC by TheoSchlaeppi

This PR introduces a new screen allowing new users to enter their information. The screen includes fields for greeting, first name, last name, email, and phone number, along with an avatar icon button for adding a profile photo.

### Architecture Overview:
- **UI Layer**: The screen layout is implemented using `LazyColumn` to allow for smooth scrolling, even if additional fields are added later. The layout includes `OutlinedTextField` components for each user input field, a centered avatar icon button for uploading a profile photo, and a `Button` for submitting the information.
  
- **Navigation**: The screen triggers navigation actions via `NavigationActions`, specifically moving to the Map screen after the user saves their information (Suggest me another screen if you don't thinks it's the better workFlow).
  
- **Future Integration with ViewModel**: The associated `ViewModel` for handling data processing and state management is planned for the next task. The ViewModel will manage form validation and data persistence.

### UI Preview:
![image](https://github.com/user-attachments/assets/1fa822e7-45ae-449d-b598-f67b9bc5b6df)

2024-11-13 09:31 UTC, LeniCadorinEpfl requested changes
This PR introduces a well-structured screen for new user onboarding, which includes form fields for personal information and a profile photo upload button. It also includes test coverage for UI components and navigation, which is excellent! Here are a few suggestions to further enhance the code:

1. Hard Coded Value:
Issue: There are several hard-coded values in the code, such as font sizes, padding, and colors. It would be great if you could extract these values and add them as constants.
2. Correct typo in Variable Name:
Issue: The variable navigaionActions is misspelled in `NewUserScreen`. Renaming it to navigationActions would be more clear. 

3.  Some additional documentation in `NewUserScreen` would be great and really helpful!

Great work overall! These are just minor suggestions that can enhance maintainability and improve user experience.

2024-11-13 09:49 UTC, TheoSchlaeppi commented
Thanks you for this fast review ! I will work on this fix now and contact you when a new review will be needed !

2024-11-14 07:39 UTC, LeniCadorinEpfl commented
Everything looks fine. It's good from my point of view, I think you can merge whenever you want.

2024-11-14 07:39 UTC, LeniCadorinEpfl approved these changes

2024-11-14 09:09 UTC, merged