Add a book from a photo using chatgpt
BookswapEPFL/Bookswap pull request #253
Opened 2024-11-22 01:27 UTC by EdenKahane

2024-11-22 02:54 UTC, EdenKahane commented
The 1.3% missing for 80% line coverage is because I'm modifying things on MainActivity to update for the new userUUID property.

2024-11-22 09:02 UTC, Chocolat2 requested changes
Overall, the code is fine, but some small changes should be addressed.

2024-11-22 09:02 UTC, Chocolat2 commented on app/src/androidTest/java/com/android/bookswap/ui/books/add/BookAdditionChoiceScreenTest.kt
Good changes on the tests, mocking the components instead of trying to instantiate them

2024-11-26 12:14 UTC, Chocolat2 approved these changes
Code looks good, requested changes were addressed properly and documentation comments were added when needed. I'm unable to test the new feature on a physical device so I trust you did test it beforehand.

2024-11-26 12:14 UTC, Chocolat2 commented on app/src/test/java/com/android/bookswap/model/BookFromChatGPTTest.kt
Required changes since app/src/main/java/com/android/bookswap/model/BookFromChatGPT.kt was modified so nothing to discuss since last review.

2024-11-27 14:26 UTC, merged