Fix of the request for the OpenAI API
BookswapEPFL/Bookswap pull request #291
Opened 2024-11-30 14:43 UTC by TheoSchlaeppi

This PR updates the JSON structure of the API request to OpenAI to ensure that the API utilizes the vision feature properly. Additionally, I have improved error handling by securing and enhancing the `catch` block across multiple layers, and added `Log.i` statements for better debugging and visibility.

Furthermore, I have adjusted the timeout of the listener to 30 seconds to prevent unnecessary timeouts.

No additional tests are needed as the existing tests already cover both success and failure scenarios. Only the error messages have been updated.

2024-12-02 11:06 UTC, LeniCadorinEpfl requested changes
Thank you very much for this nice PR that introduces significant improvements to the API request structure and error handling. The changes are clear, well-documented, and address critical areas like enhancing stability, debugging, and maintaining compatibility.

I think you could abstract the JSON Construction: Consider moving the JSON construction logic into a helper method or utility class. This would help avoid duplicating similar patterns in ChatGPTApiService.kt and improve the code’s maintainability and readability.
Overall, the code is excellent and thoughtfully implemented. Great work, and thank you for contributing these valuable enhancements!

2024-12-02 12:07 UTC, TheoSchlaeppi commented
Thank you for your review, i put the creation of the Json request in the file JSONUtils.kt

2024-12-03 21:39 UTC, LeniCadorinEpfl commented
Everything looks good to me. Thank you for your work! It can definitely be merged.

2024-12-03 21:39 UTC, LeniCadorinEpfl approved these changes

2024-12-04 09:32 UTC, merged