Implement the Google Sign-In
BookswapEPFL/Bookswap pull request #51
Opened 2024-10-10 11:19 UTC by LeniCadorinEpfl

This PR introduces a new screen, the **SignIn screen**. It uses Firebase Authentication and allows users to log in to the app using their Google account.

**Key changes:**

**Sign In Screen UI:**
Implemented the title and logo using composable functions.

**Google Sign-In Button:**
Using Firebase Authentication, it enables connection to a Google account.

**Future Navigation:**
Once navigation is implemented, the commented part can be added and slightly adjusted. After the user signs in, they should be navigated to the Map screen.

**Checklist:**
- [ ] CI passes
- [ ] Structure is correct
- [ ] Tests for the added code are complete

2024-10-10 11:37 UTC, matiisalv approved these changes
Brillant work , very clear  and well designed .
In the rememberFirebaseAuthLauncher, the exception handling only logs the error with Log.e. You could provide more user feedback within the UI to notify users about login issues directly:
Toast.makeText(context, "Authentication failed. Please try again.", Toast.LENGTH_LONG).show()
And maybe you should change the name of the testAg to be more specific instead of repeating it 
Two test don't pass please see to it

2024-10-11 00:46 UTC, EdenKahane requested changes
Apart from the weird CI bug, it's perfect !

2024-10-11 00:46 UTC, EdenKahane commented on .github/workflows/ci.yml
> +      - name: Wait for emulator to fully start
This cause an infinite time loop apparently

2024-10-15 22:16 UTC, EdenKahane approved these changes
Everything seems fixed, congratulation for fixing the CI problem !

2024-10-16 08:53 UTC, merged