Add user profile screen, userVM and user data class
BookswapEPFL/Bookswap pull request #71
Opened 2024-10-10 17:32 UTC by Chocolat2

Add user profile screen and edit profile alert dialogue
Add user data class and view model
Add basic tests for user data class

2024-10-10 19:54 UTC, EdenKahane requested changes
The code is very clean ! 
The firebase part is commented out for unknown reason 
There is no firebase tests implemented. [Here](https://github.com/BookswapEPFL/Bookswap/blob/main/app/src/test/java/com/android/sample/model/BooksFirestoreRepositoryTest.kt) is an example of firestore mock that should be helpful.

2024-10-10 19:54 UTC, EdenKahane commented on app/src/main/java/com/android/bookswap/model/userViewModel.kt
> +    firebaseConnection.getUserUidByEmail(user.email).addOnSuccessListener {
All the firebase part are missing ?

2024-10-10 19:54 UTC, EdenKahane commented on app/src/test/java/com/android/bookswap/data/UserTest.kt
> +  fun checkAssign() {
What is the purpose of this test ?

2024-10-17 15:48 UTC, oliveja22 commented on app/src/main/java/com/android/bookswap/model/userViewModel.kt
> +            this.uid = it.documents[0].id
If you are going to comment so much stuff, I think it would be better to remove it, it makes reading anything a lot more complicated.

2024-10-17 15:52 UTC, oliveja22 commented on app/src/main/java/com/android/bookswap/model/userViewModel.kt
> +            this.uid = it.documents[0].id
I thought it was all finished, please ignore this

2024-10-17 21:13 UTC, EdenKahane requested changes
Clean code ! There is a slight unnecessary string function for a data class.
Also next time, please write 2 PR of the two tasks, instead of just one big PR

2024-10-17 21:13 UTC, EdenKahane commented on app/src/main/java/com/android/bookswap/data/DataUser.kt
> +  override fun toString(): String {
With kotlin dataclass, there is no need to override this

2024-10-17 21:13 UTC, EdenKahane commented on app/src/main/java/com/android/bookswap/data/DataUser.kt
> +  fun printFull1Line(): String {
This is also unnecessary

2024-10-18 00:40 UTC, EdenKahane approved these changes
Now everything seems perfect.
Thanks !

2024-10-18 00:45 UTC, merged